#Website Scraping
venue-name.nationwide=Nationwide Arena
venue-name.kemba=KEMBA Live!
venue-name.newport=Newport Music Hall
venue-name.ar-bar=A&R Music Bar
venue-name.ace=Ace Of Cups
venue-name.sn-stage=Short North Stage
venue-name.ballet-met=Ballet MET

url.nationwide=https://www.nationwidearena.com/events
url.kemba=https://promowestlive.com/columbus/kemba-live
url.newport=https://promowestlive.com/columbus/newport-music-hall
url.ar-bar=https://promowestlive.com/columbus/a-and-r-music-bar
url.ace=https://aceofcupsbar.com
url.sn-stage=https://www.capa.com/event-calendar/?term_producing_organization%5B%5D=short-north-stage&start_date={start-date}&end_date={end-date}
url.ballet-met=https://www.capa.com/event-calendar/?term_producing_organization%5B%5D=balletmet&start_date={start-date}&end_date={end-date}

#API
api.discovery.url=https://app.ticketmaster.com/discovery/v2/events.json?venueId={VENUE_ID}&apikey={API_KEY}
api.discovery.key=${DISCOVERY_API_KEY}
api.discovery.nationwide.venue-id=KovZpZA6kelA
api.discovery.nationwide.source-name=Nationwide Arena

#Database
dynamodb.events.table=ColumbusEvents

spring.application.admin.enabled=false
